Proposal of .lvtext Slice Annotation file format specs
openvpi/LabelVoice pull request #3
Opened 2022-10-04 15:59 UTC by RigoLigoRLC

2022-10-05 14:07 UTC, yqzhishen commented on docs/spec.zh-CN.md
> +    type: text # TODO: Text类型在被切开时的行为？
This property can be removed since the label text is always stored as strings. Input validations and checks can be done with label schema defined in the `.lvproj` file.

2022-10-05 14:22 UTC, yqzhishen commented on docs/spec.zh-CN.md
> +**i.** 最后一个数据点作为右边界使用。此时text字段应当为null。若软件读入后时间最靠后的切点不为null，则自动认定其为右边界并将其设为null。
The last boundary is not necessary to be stored because its `time` property always equals to the length of the slice. If you want to make this file format more self-contained, you can consider storing source audio path and the referring time range of this slice, like the project path stored in the `.lvitem` file. These properties are used to make these files more easy to be read/wrote alone, and are ignored when they are opened with a project.

2022-10-05 14:27 UTC, yqzhishen commented on docs/spec.zh-CN.md
> +        time: 0.0000
`time` does not seem to be a good property name because it can be confused with `duration` here. Consider using `pos` or `position`.

2022-10-05 14:27 UTC, RigoLigoRLC commented
> The last boundary is not necessary to be stored because its time property always equals to the length of the slice.
`time` property is the time point of cutting, not the duration of a slice in the annotation layer.

> you can consider storing source audio path and the referring time range of this slice, like the project path stored in the .lvitem file. These properties are used to make these files more easy to be read/wrote alone, and are ignored when they are opened with a project.
Of course, great idea. So the file would store basic metadata for the audio slice, like the file path and time range. These data will be used when editing independent of the project, but would be ignored inside project, and overwritten by the property of item if the two aren’t the same. Do you approve this rule?

> 2022年10月5日 22:22，yqzhishen ***@***.***> 写道：
> 
> 
> @yqzhishen commented on this pull request.
> 
> In docs/spec.zh-CN.md <https://github.com/openvpi/LabelVoice/pull/3#discussion_r987983301>:
> 
> > +**1.** ***layers*** 所有标注层（类比 Praat 中 TextGrid 的 Tier）。每一层中均可切割出若干分段，并冠以一个内容字符串。
> +
> +**2.** *(layer对象)* 一个标注层。必须包含不重复的名称（*name*，字符串）、`text`/`time`中的一种类型（*type*，字符串）
> +和该层中所有切割标记的列表（*slices*，列表）。slices中的切点应当允许乱序。
> +
> +**3.** *(slice对象)* 一个切割标记点。必须包含一个编号（*id*，整型）<sup>[i]</sup>、以秒计的切割的时间点（*time*，浮点数）
> +和该切割点右侧的块包含的内容字符串（*text*，字符串或null）<sup>[ii]</sup>。
> +
> +**4.** ***groups*** 切点绑定（列表）。绑定后的一组切点在移动一个切点时其他点会跟随移动相同的量。
> +
> +**5.** *(group对象)* 子元素全为整型的列表。如有不是列表的group对象，则忽略。如group列表中的元素有非整型的或者不对应于任何一个切割点的，则忽略。
> +如果文件中出现一个切点被绑定到多个组中，则应按读取顺序，将其从原来所属组中拆除，排入新组。
> +
> +### 备注
> +
> +**i.** 最后一个数据点作为右边界使用。此时text字段应当为null。若软件读入后时间最靠后的切点不为null，则自动认定其为右边界并将其设为null。
> The last boundary is not necessary to be stored because its time property always equals to the length of the slice. If you want to make this file format more self-contained, you can consider storing source audio path and the referring time range of this slice, like the project path stored in the .lvitem file. These properties are used to make these files more easy to be read/wrote alone, and are ignored when they are opened with a project.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/openvpi/LabelVoice/pull/3#pullrequestreview-1131520406>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ALYTVUTH6X3NOFNGYRVJ7DDWBWFJXANCNFSM6AAAAAAQ4W7IIE>.
> You are receiving this because you authored the thread.
>

2022-10-05 14:28 UTC, yqzhishen requested changes
Please
1. Fetch the latest changes from the upstream and resolve the conflicts
2. Make some changes according to the specs of `.lvproj` and `.lvitem` file and single line comments
3. Simplify the example
4. Unify the description formats with the other part of the document if possible
Thanks!

2022-10-05 14:31 UTC, yqzhishen commented
> The last boundary is not necessary to be stored because its time property always equals to the length of the slice.
> `time` property is the time point of cutting, not the duration of a slice in the annotation layer.
> you can consider storing source audio path and the referring time range of this slice, like the project path stored in the .lvitem file. These properties are used to make these files more easy to be read/wrote alone, and are ignored when they are opened with a project.
> Of course, great idea. So the file would store basic metadata for the audio slice, like the file path and time range. These data will be used when editing independent of the project, but would be ignored inside project, and overwritten by the property of item if the two aren’t the same. Do you approve this rule?
> […](#)
> 2022年10月5日 22:22，yqzhishen ***@***.***> 写道： @yqzhishen commented on this pull request. In docs/spec.zh-CN.md <[#3 (comment)](https://github.com/openvpi/LabelVoice/pull/3#discussion_r987983301)>: > +**1.** ***layers*** 所有标注层（类比 Praat 中 TextGrid 的 Tier）。每一层中均可切割出若干分段，并冠以一个内容字符串。 + +**2.** *(layer对象)* 一个标注层。必须包含不重复的名称（*name*，字符串）、`text`/`time`中的一种类型（*type*，字符串） +和该层中所有切割标记的列表（*slices*，列表）。slices中的切点应当允许乱序。 + +**3.** *(slice对象)* 一个切割标记点。必须包含一个编号（*id*，整型）<sup>[i]</sup>、以秒计的切割的时间点（*time*，浮点数） +和该切割点右侧的块包含的内容字符串（*text*，字符串或null）<sup>[ii]</sup>。 + +**4.** ***groups*** 切点绑定（列表）。绑定后的一组切点在移动一个切点时其他点会跟随移动相同的量。 + +**5.** *(group对象)* 子元素全为整型的列表。如有不是列表的group对象，则忽略。如group列表中的元素有非整型的或者不对应于任何一个切割点的，则忽略。 +如果文件中出现一个切点被绑定到多个组中，则应按读取顺序，将其从原来所属组中拆除，排入新组。 + +### 备注 + +**i.** 最后一个数据点作为右边界使用。此时text字段应当为null。若软件读入后时间最靠后的切点不为null，则自动认定其为右边界并将其设为null。 The last boundary is not necessary to be stored because its time property always equals to the length of the slice. If you want to make this file format more self-contained, you can consider storing source audio path and the referring time range of this slice, like the project path stored in the .lvitem file. These properties are used to make these files more easy to be read/wrote alone, and are ignored when they are opened with a project. — Reply to this email directly, view it on GitHub <[#3 (review)](https://github.com/openvpi/LabelVoice/pull/3#pullrequestreview-1131520406)>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ALYTVUTH6X3NOFNGYRVJ7DDWBWFJXANCNFSM6AAAAAAQ4W7IIE>. You are receiving this because you authored the thread.

Yes, and that is what I mean.

2022-10-07 15:13 UTC, RigoLigoRLC commented
Resolved requested review changes. Please review this PR again, thanks

2022-10-07 15:28 UTC, yqzhishen approved these changes

2022-10-07 15:30 UTC, merged

2022-10-11 09:24 UTC, RigoLigoRLC commented
Considering there may be a need of `time` type (in which the blocks automatically display their respective lengths, in seconds) I left this property for expansion. Unfortunately I forgot to add specs for `time` typed layers… If you consider it unnecessary then I can safely remove this property.

> 2022年10月5日 22:07，yqzhishen ***@***.***> 写道：
> 
> 
> @yqzhishen commented on this pull request.
> 
> In docs/spec.zh-CN.md <https://github.com/openvpi/LabelVoice/pull/3#discussion_r987966562>:
> 
> > @@ -104,3 +104,114 @@
>  </Project>
>  ```
>  
> +## 4 音频切片标注文件（.lvtext）
> +```yaml
> +# LabelVoice Slice Annotation File
> +version: 1
> +layers: # [1]
> +  - name: 句子 # [2]
> +    type: text # TODO: Text类型在被切开时的行为？
> This property can be removed since the label text is always stored as strings. Input validations and checks can be done with label schema defined in the .lvproj file.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/openvpi/LabelVoice/pull/3#pullrequestreview-1131494914>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ALYTVUWSAWGEXGGT5GFNKQ3WBWDRNANCNFSM6AAAAAAQ4W7IIE>.
> You are receiving this because you authored the thread.
>

2022-10-11 13:27 UTC, yqzhishen commented
> Considering there may be a need of `time` type (in which the blocks automatically display their respective lengths, in seconds) I left this property for expansion. Unfortunately I forgot to add specs for `time` typed layers… If you consider it unnecessary then I can safely remove this property.

Model classes should just store, read and write the raw data regardless of the relations and bindings. For `time` layers, the data validity, namely that the text represents its duration, should be guaranteed by the ViewModel, which is responsible for data bindings and validations. The layer itself does not need to know its type and it stores all texts as strings, which simplifies the data model. By the way, I planned to add a `Validate()` method for each model classes. This method validates some (but possibly not all) properties and fields after deserializing and before serializing.